### ISSUE TITLE
:poop: Upper Bound for data_generation.py>> INTEGER VARIABLE Zm_t  -->  zmax

### ISSUE THREAD

**Issue by b4ghir1** [MxHbm/Management-Science#14]
Unfortunately this code doesn't work: 
`self.Zm_t = model.addVars(MP, T, vtype=GRB.INTEGER, lb=0, ub=parameters_FirstStage.zmax, name="Zm_t")`

this works:
`self.Zm_t = model.addVars(MP, T, vtype=GRB.INTEGER, lb=0, name="Zm_t")`

Any ideas?

**Comment by MxHbm** [comment]
Wie wäre es wenn du eine Schleife erstellst und jede Variable einzeln erzeugst? Dann kannst du auch auf die direkten Listen Elemente zugreifen mit: ub=parameters_FirstStage.zmax[1]

also: 

for i in range MP: 
for j in range T: 
model.addVar(MP, T, vtype=GRB.INTEGER, lb=0, ub=parameters_FirstStage.zmax[j], name="Zm_t")
