### ISSUE TITLE
scenario probability calculation

### ISSUE THREAD

**Issue by b4ghir1** [MxHbm/Management-Science#20]
Rho_s gibt als dummy aktuell nur eine Gleichverteilung (1/243) aus. 

Ich hab es so verstanden, dass jedes Szenario mit den jeweiligen Wahrscheinlichkeit multipliziert wird. (oder?)
![grafik](https://github.com/MxHbm/Management-Science/assets/52173490/5757abaa-4e66-4a35-a7c6-0f5d7e3b865f)
![grafik](https://github.com/MxHbm/Management-Science/assets/52173490/e36899bd-77e4-455e-aed5-0495512b0159)

Somit ergeben sich dass 243 Wahrscheinlichkeiten.

Möglicherweise sollte wir mal darüber nachdenken keine reine Listen mehr zu verwenden, sondern eine explizitere Darstellung der Werte (möglicherweise in einem Dictonary oder DataFrame), sodass es einfacher wird zu sagen, welchen Wert wir gerade betrachten..

**Comment by MxHbm** [comment]
Ich habe eigentlich genau das gemacht, was in dem Paper beschrieben wird. Und da kommen am Ende auch nur 9 reduzierte Szenarios raus - die Szenarien sind nicht gleichverteilt, sondern ergeben sich als multipolikation. Für den Algorithmus/MIP brauchst du nur die Wahrscheinlichkeiten und die Werte der reduced scenarios

**Comment by b4ghir1** [comment]
okay, gut :) 

Vielleicht können wir nächste Woche noch mal darüber reden :)

**Comment by MxHbm** [comment]
Yes! Lass erstmal das Model zu Ende aufstellen und dann besprechen wir die genaue Darstellung!

**Comment by MxHbm** [comment]
scenarios are integrated in the model
