### ISSUE TITLE
ENB objective function

### ISSUE THREAD

**Issue by b4ghir1** [MxHbm/Management-Science#21]
Hier stellt sich mir bei der Berechnung noch die Frage, inwiefern ich Rho_s mit in der Summe betrachten soll - oder ob Rho_s hier als 243-dimensionaler Vektor gesehen wird?

![grafik](https://github.com/MxHbm/Management-Science/assets/52173490/e33ba76e-d638-4571-91db-221cb0439395)

**Comment by b4ghir1** [comment]
in die Summe ziehen

**Comment by b4ghir1** [comment]
im Paper beachten: Index von OS steht verdreht im Paper -> richtig: OS_sflt

![grafik](https://github.com/MxHbm/Management-Science/assets/52173490/e5991574-b6f1-434c-90b4-5cc3fbf171df)

**Comment by MxHbm** [comment]
kann der issue geclosed werden?

**Comment by b4ghir1** [comment]
Ja.
