### ISSUE TITLE
values for Family demand for distribution center l on day t under scenario s. (scenario dependent, stage2)

### ISSUE THREAD

**Issue by b4ghir1** [MxHbm/Management-Science#22]
Werte festlegen:

![grafik](https://github.com/MxHbm/Management-Science/assets/52173490/6fed658e-5481-411d-a2ed-7d7902ddd0a7)

**Comment by MxHbm** [comment]
Indeed this is weird, because in the results of the case the authors only present a solution which is dp_s_f, so there is no dependency from the distribution centre and the time
