### ISSUE TITLE
CHange variable names to names **without underscore**

### ISSUE THREAD

**Issue by MxHbm** [MxHbm/Management-Science#25]
In my opinion this looks quite bad and makes it even more confusing: 
- dps_f_l_t[s,f,l,t1] or
- OSs_f_l_t[s,f,l,t1]

**Comment by b4ghir1** [comment]
I would recommend something like that:

- dp_s_f_l_t[s,f,l,t1] or
- dp_sflt[s,f,l,t]

so that you can see name_indices of variables at one glance

What would you prefer?

**Comment by MxHbm** [comment]
I would prefer clean look:  dp_sflt[s,f,l,t] -> dp[s,f,l,t]

then you dont have any information doubled, and we can use the paper notation and we get errors as well haha

**Comment by MxHbm** [comment]
was done in a recent merge
