### ISSUE TITLE
💩 2 wrong constraints in the paper - indices don't make sense!! 

### ISSUE THREAD

**Issue by MxHbm** [MxHbm/Management-Science#27]
In the paper there are two constraints, which cant be implemented in Python, because either the indices are missing or the wrong Sets are used! 

These are the two!  So Constraints 1.9 

model.addConstrs(decisionVariables_SecondStage.IDs_f_l_t[s,f,l,t] == data.i_0[f][l] + gp.quicksum(decisionVariables_FirstStage.DVf_l_t[f,l,t1] for t1 in T if (t1+data.tau[l]) <= t) -
                    gp.quicksum(parameters_SecondStage.dps_f_l_t[s,f,l,t1] for t1 in T if (t1) <= t) - 
                    gp.quicksum(decisionVariables_SecondStage.SO_sflt[s,f,l,t1] for t1 in T if t1 <= t) - 
                    gp.quicksum(decisionVariables_SecondStage.OSs_f_l_t[s,f,l,t1] for t1 in T if t1 <= t) for s in S for f in F for l in L for t in T)
    

    # INDEX OF TAU WAS WRONG !! i INSTEAD OF l

    '''In any DC, fresh and dry warehouse size limitations may arise; this is modeled by constraint'''

    model.addConstrs(gp.quicksum(decisionVariables_SecondStage.IDs_f_l_t[s,f,l,t] for f in F if data.fty[f] == i) <= data.imax[i][l] for s in S for l in L for i in FT for t in T)
    # RUNNING PARAMETER FOR T IS MISSING!!!

**Comment by b4ghir1** [comment]
tau_i korrigieren zu tau t (wie gedacht)

**Comment by b4ghir1** [comment]
mögliche Fehler gefunden: 

+ und - vertauscht:

![grafik](https://github.com/MxHbm/Management-Science/assets/52173490/673b2f9f-4932-499a-8829-861c7c717ae8)

![grafik](https://github.com/MxHbm/Management-Science/assets/52173490/fece1985-0bc4-4732-aada-b3ce66c7767c)

**Comment by MxHbm** [comment]
chnaged in the model long time ago and from the prof approved
