### ISSUE TITLE
what about FW?

### ISSUE THREAD

**Issue by b4ghir1** [MxHbm/Management-Science#29]
What is FW? 
Can anyone find a definition ?

**Comment by b4ghir1** [comment]
for example here:
![grafik](https://github.com/MxHbm/Management-Science/assets/52173490/86627a1a-6750-4e67-86c4-5362a51804bd)

**Comment by b4ghir1** [comment]
bedeutet es Factory Warehouse ?????
![grafik](https://github.com/MxHbm/Management-Science/assets/52173490/394928d5-478d-48a9-bc75-092644babe33)

**Comment by MxHbm** [comment]
ja hat ja prof Becker bestätigt, dass FW gleich Factory Warehouse ist
