### ISSUE TITLE
Constraint 1.1 fy(fpr_m)

### ISSUE THREAD

**Issue by b4ghir1** [MxHbm/Management-Science#40]
Was meint das? Ergibt fy(fpr_m) Sinn?

Brauchen wir nicht nur als Divisor fy oder fpr_m ?

![grafik](https://github.com/MxHbm/Management-Science/assets/52173490/ceefd356-dbf2-4c5a-a293-98417332df72)

![grafik](https://github.com/MxHbm/Management-Science/assets/52173490/f2880be1-0a8a-463f-bc2b-e77fdc7f6452)

**Comment by MxHbm** [comment]
Ich glaube dass es reicht nur fy zu betrachtet, wenn man auf die Bedeutung der variablen schaut:  RAW MILK  = Produktion Quantity / Leverage. 

also wenn fy für käse sagen Wir mal 0,2 ist: dann wäre die Gleichung:  5 Ton Milch = 1 Käse / 0.2 Käse/ Ton Milch

**Comment by MxHbm** [comment]
schon erledigt
