### ISSUE TITLE
Constraint 1.2: fpr_m == f

### ISSUE THREAD

**Issue by b4ghir1** [MxHbm/Management-Science#41]
Wie ist das gemeint? Und wie wollen wir das umsetzen? Aktuell kommt glaube ich nicht das gewünschte Ergebnis raus.

![grafik](https://github.com/MxHbm/Management-Science/assets/52173490/8447a747-729f-4729-b58f-a687900ee129)

![grafik](https://github.com/MxHbm/Management-Science/assets/52173490/f598c5a6-e645-44e0-8a48-d2ede3c47af8)

![grafik](https://github.com/MxHbm/Management-Science/assets/52173490/d867d210-e704-4d01-bbf9-3b7be42423fb)

**Comment by MxHbm** [comment]
Habe ich mir auch gerade angeschaut, das soll ja nur bedeuten, dass der Index von f_pr f entspricht, also wenn ich mir die Produktion von milk anschaue, dann soll auch nur die zugehörige Fabrik also die zweite betrachtet werden :D oder? Ich glaube man kann das mit einem zweiten if lösen

**Comment by b4ghir1** [comment]
Könnte das eine Lösung sein? Was sagst du dazu, Max?
![grafik](https://github.com/MxHbm/Management-Science/assets/52173490/96baf574-d16d-455a-868a-a3fcd422d46a)
![grafik](https://github.com/MxHbm/Management-Science/assets/52173490/dbba45d0-b4d2-416b-85c7-b0aea72a4ad0)

**Comment by MxHbm** [comment]
Mapping möglich oder einfach nur die Übergabe von f == m oder so :D
