### ISSUE TITLE
Constraint 1.7: alpha[m] -1 ?

### ISSUE THREAD

**Issue by b4ghir1** [MxHbm/Management-Science#42]
Muss hier noch '-1' ergänzt werden, oder reicht es so?

![grafik](https://github.com/MxHbm/Management-Science/assets/52173490/6a750e3f-63de-4422-aef8-6da59b2f817c)

![grafik](https://github.com/MxHbm/Management-Science/assets/52173490/f695d465-93a1-4248-bc93-62ba2afa67d0)

![grafik](https://github.com/MxHbm/Management-Science/assets/52173490/390a986c-844b-4f67-b7ff-07ddd80683aa)

**Comment by MxHbm** [comment]
Das heißt doch dass diese constraints nur greifen, wenn setup erforderlich ist und damit nur für powdered milk oder?

**Comment by b4ghir1** [comment]
Ja, das sehe ich auch so.

Meine Frage zielt auf das 
`for t1 in range((data.alpha[m])`
ab, und ob wir hier noch - wie im Paper beschrieben - die -1 ergänzen wollen und wenn ja, welchen Sinn das hat? 
`for t1 in range((data.alpha[m] - 1)`

**Comment by MxHbm** [comment]
Müssen wir nicht, da wir bei Python mit dem Range Befehl eh schon über weniger Werte iterieren, wenn range(2), dann sind ja die werte 0 und 1 und in dem Fall hat dann nur die eine Auswirkung
