### ISSUE TITLE
🚧 How to deal with weird running parameters: Constraints 1..10

### ISSUE THREAD

**Issue by MxHbm** [MxHbm/Management-Science#51]
In diesen Nebenbedingungen sind komische Laufvariablen angegeben: 

![Bildschirmfoto 2024-05-17 um 11 38 04](https://github.com/MxHbm/Management-Science/assets/113389275/4cc588b4-cd9f-482a-a8f9-dff0af91b522)

Daraus resultiert ein nicht klarer Umgang mit den Constraints in python: 

        model.addConstrs((decisionVariables_FirstStage.IF[f,t] 
                        <= gp.quicksum((decisionVariables_FirstStage.DV[f,l,t1]
                                        / parameters_FirstStage.omega_fw[f])
                                        *(t + parameters_FirstStage.omega_fw[f] - parameters_FirstStage.hl) for t1 in range(t - parameters_FirstStage.omega_fw[f] + 1, t) for l in L) 
                        +  gp.quicksum(decisionVariables_FirstStage.DV[f,l,t2] for t2 in range(t + 1, t + parameters_FirstStage.omega_fw[f] + 1) for l in L if t2 <= parameters_FirstStage.hl) 
                        for f in F for t in T 
                        if (parameters_FirstStage.fty[f] == 1) and (t + parameters_FirstStage.omega_fw[f] > parameters_FirstStage.hl)),
                        'Constraint_1.10b')

Die konkrete Frage wie soll range() eingestellt werden?

**Comment by b4ghir1** [comment]
Aktuell ist es ja so eingestellt:

1. (oben links):  `for t1 in range(t+1,t+parameters_FirstStage.omega_fw[f]) `
2.  (oben rechts):   `if (parameters_FirstStage.fty[f] == 1) and (t + parameters_FirstStage.omega_fw[f] <= parameters_FirstStage.hl))`
3. (unten links): `for t1 in range(t - parameters_FirstStage.omega_fw[f] + 1,  t)`
4. (unten rechts); `for t2 in range(t + 1, t + parameters_FirstStage.omega_fw[f] + 1)  for l in L if t2 <= parameters_FirstStage.hl)`

Meinst du, dass die Begründung oder die Sinnhaftigkeit dieser Laufvariablen sich dir nicht erschließt?  
(Meiner Meinung nach ist es akutell so umgesetzt wie im Paper, oder?

**Comment by b4ghir1** [comment]
Ah, okay. Ich sehe gerade deinen #50, da hast du ja eine +1 hinzugefügt:

![grafik](https://github.com/MxHbm/Management-Science/assets/52173490/12140009-9755-481e-8dda-6de1d9dceb98)

**Comment by b4ghir1** [comment]
Ich versuche es mal mathematisch und pythonisch nachzuvollziehen;

![grafik](https://github.com/MxHbm/Management-Science/assets/52173490/0b5fc7cf-ab29-454b-8df5-b89703ef3649)


1. 
![grafik](https://github.com/MxHbm/Management-Science/assets/52173490/e051c285-1035-4b79-8ae2-67e08b45ef0c)

für t=0, `if (0+omega) <= 29`
t1 = {0+1, ...., 0+7}            ==`if`==>  t1 = {0+1, ...., 0+7}       // minimum
t1 = {0+1, ...., 0+100}       ==`if`==>  t1 = {0+1, ...., 0+29}    // maximum

für t=29, `if (29+omega) <= 29`
t1 = {29+1, ...., 29+7}            ==`if`==>  t1 = {29+1, ...., 29+7}       // minimum
t1 = {29+1, ...., 29+100}       ==`if`==>  t1 = {29+1, ...., 29}    // maximum

für t=22, `if (29+omega) <= 29`            // unter Beachtung der Bedingung
t1 = {22+1, ...., 22+7}            ==`if`==>  t1 = {22+1, ...., 22+7}       // minimum
t1 = o/o                                  // für shelf_live > hl --> diese Constraints finden keine Beachtung im Modell

Also meines Verständnis nach, finden hier nur die Constraints im Modell Beachtung, die auch aufgrund des betrachteten Zeitraums relevant sind. 

Ah, aber die Ergänzung mit "+1" trägt natürlich dazu bei, dass Python den kompletten Bereich als Range betrachtet, der im mathematischen Modell betrachtet wird.

(sorry für den längeren Post und meine Gedankengänge, die ich einfach 1:1 hier aufgeschrieben habe :D )

**Comment by MxHbm** [comment]
und was denkst du nehmen wir die plus 1 mit rein?

**Comment by MxHbm** [comment]
Sollte so funktionieren wie momentan implementiert
