### ISSUE TITLE
Model is infeasible or unbounded

### ISSUE THREAD

**Issue by b4ghir1** [MxHbm/Management-Science#53]
Output of infeasible.ilp:

> \ Model FirstStage_copy
> \ LP format - for model browsing. Use MPS format to capture full model detail.
> Maximize
>  
> Subject To
>  Constraint_1.9a[8,3,0,0]: - SOs_f_l_t[8,3,0,0] + IDs_f_l_t[8,3,0,0] = 33
>  Constraint_1.9b[8,0,1,0]: IDs_f_l_t[8,2,0,0] + IDs_f_l_t[8,3,0,0] <= 10
> Bounds
>  IDs_f_l_t[8,3,0,0] free
> End

It seems like ID_sflt is  unbound. Maybe the given data are not feasible for our model or  the constraints are not right at all.

It seems that ID_sflt has a problem at time step 0. 

How do we fix that?  Any ideas?

**Comment by b4ghir1** [comment]
@MxHbm kann es sein, dass es an der ScenarioReduction liegt? (Hab da noch nicht detailliert reingeschaut)

Anscheinend ist  `IDs_f_l_t[8,3,0,0] free`.
Das bedeutet ja, dass ID für (mindestens) t=0, l=0 in Szenario 9 nicht ausreichend definiert ist, oder?

**Comment by b4ghir1** [comment]
ok, das mit den ScenarioReduction-Values ist nicht sooo wahrscheinlich. 
Vielleicht fehlt eine Gleichung? Oder eine ist zu restriktiv?

**Comment by MxHbm** [comment]
mmh ich denke eher die Werte aus dem paare hauen nicht ganz hin, eventuell legen wir morgen mal extrem große werte fest unf schauen mal ob es läuft und dann bauen wir schnell einen Sachsenmilch case?

**Comment by b4ghir1** [comment]
Liegt das angesprochene Arbitrage an diesen Werten? 

Revenue: 
![image](https://github.com/MxHbm/Management-Science/assets/52173490/66918a3d-6738-40a3-ad1d-75cf94db81a1)

Cost:
![image](https://github.com/MxHbm/Management-Science/assets/52173490/b3c3afc9-a2f2-47c4-a8b3-d60636f44d8a)

Wenn ich die Kosten auf 20 setze, kann ich auch die Upper Bound von RS rausnehmen.

**Comment by b4ghir1** [comment]
Kurze Auswertung von rsc: 
rsc >= 4.3  ==> feasible

[logging.log](https://github.com/MxHbm/Management-Science/files/15461488/logging.log)

**Comment by b4ghir1** [comment]
Aber da stellt sich natürlich die Frage, warum genau das die Grenze für die Feasibility ist....

**Comment by MxHbm** [comment]
geklärt aber neue Probleme aufgekommen!
