### ISSUE TITLE
:rotating_light: Generation of values with no information from the paper 

### ISSUE THREAD

**Issue by MxHbm** [MxHbm/Management-Science#6]
How do we handle the parameters as iwip, where we don't have any information at all about values?

**Comment by b4ghir1** [comment]
-> Werte müssen nicht 1:1 aus dem Paper übernommen werden.
-> Können eigene Case Study kreieren
--> beispielhafter Datensatz kann erstellt werden (Dresden, Görlitz, ...) -> Zufallsdaten erstellen

**Comment by MxHbm** [comment]
closed issue
