### ISSUE TITLE
graphs: Contraint Values (RHS) and Var Values (Obj)

### ISSUE THREAD

**Issue by b4ghir1** [MxHbm/Management-Science#65]
Maybe someone can find the reason why our model doesn't work properly...

**Comment by b4ghir1** [comment]
Variables:

![Zm_t-family_aggregated_model](https://github.com/MxHbm/Management-Science/assets/52173490/602503d4-9862-4d13-96e5-a7faf56c209e)
![Zm_t-detailed_model](https://github.com/MxHbm/Management-Science/assets/52173490/4de84fc5-4cc0-4b38-9cb3-a8634436289e)
![Z2m_t-family_aggregated_model](https://github.com/MxHbm/Management-Science/assets/52173490/fc5386d5-440f-426f-ad5b-90a7a2769c45)
![Z2m_t-detailed_model](https://github.com/MxHbm/Management-Science/assets/52173490/aed6fdc7-c8a1-4f81-8abf-83de5fd6d58d)
![Z1m_t-family_aggregated_model](https://github.com/MxHbm/Management-Science/assets/52173490/10a7462a-01c3-4022-b42e-d003f67fe99b)
![Z1m_t-detailed_model](https://github.com/MxHbm/Management-Science/assets/52173490/aed48dd7-5f19-42c9-aa70-e2def49a7dfe)
![Ym_t-family_aggregated_model](https://github.com/MxHbm/Management-Science/assets/52173490/8af91c91-4414-4508-9aea-895abff30c7c)
![Ym_t-detailed_model](https://github.com/MxHbm/Management-Science/assets/52173490/5601623f-5eb7-454b-8f82-cfad6f069780)
![Vi_l_t-family_aggregated_model](https://github.com/MxHbm/Management-Science/assets/52173490/2cc484da-d9d6-4172-bc50-c26afaebe32c)
![Vi_l_t-detailed_model](https://github.com/MxHbm/Management-Science/assets/52173490/59240ac8-e56e-452e-a8c9-0ad90f3ba5da)
![VDi_l_t-family_aggregated_model](https://github.com/MxHbm/Management-Science/assets/52173490/4e79e238-16b6-4367-a08c-581fbd526e4b)
![VDi_l_t-detailed_model](https://github.com/MxHbm/Management-Science/assets/52173490/3c170b50-f940-4e82-b862-afaf210736b4)
![TRi_l_t-family_aggregated_model](https://github.com/MxHbm/Management-Science/assets/52173490/cf5cfa5d-c3da-4bef-a047-1ff7eab1e438)
![TRi_l_t-detailed_model](https://github.com/MxHbm/Management-Science/assets/52173490/8df5ec32-4996-42ed-b90f-1f773f1b903d)
![TRDi_l_t-family_aggregated_model](https://github.com/MxHbm/Management-Science/assets/52173490/160093a4-d226-4aac-94c9-2b4927d4cfc5)
![TRDi_l_t-detailed_model](https://github.com/MxHbm/Management-Science/assets/52173490/43485435-e047-44fb-b557-a0284406a4c7)
![TCOST-family_aggregated_model](https://github.com/MxHbm/Management-Science/assets/52173490/09bc63e1-3eae-4448-83d1-6f8419159881)
![TCOST-detailed_model](https://github.com/MxHbm/Management-Science/assets/52173490/ff339454-579b-4546-9000-7d801f530598)
![SOs_f_l_t-family_aggregated_model](https://github.com/MxHbm/Management-Science/assets/52173490/19d079f4-e5e4-4f3f-8568-bee6fe73fea2)
![SOs_f_l_t-detailed_model](https://github.com/MxHbm/Management-Science/assets/52173490/ad41d8bd-9a85-4b2a-bc5e-32ebe469187b)
![SODs_p_l_t-family_aggregated_model](https://github.com/MxHbm/Management-Science/assets/52173490/69f63baa-9d5c-427d-9943-4bf7eebe9b2d)
![SODs_p_l_t-detailed_model](https://github.com/MxHbm/Management-Science/assets/52173490/117145da-4fe5-4ee8-bdd6-28ea61e961d7)
![SN-family_aggregated_model](https://github.com/MxHbm/Management-Science/assets/52173490/8eff9dfa-bdde-4f51-993e-0469cfec5b6b)
![SN-detailed_model](https://github.com/MxHbm/Management-Science/assets/52173490/4887e7df-56ec-4440-9202-70008942d719)
![SAs_f_l_t-family_aggregated_model](https://github.com/MxHbm/Management-Science/assets/52173490/7241ac9d-796a-4971-9383-f74abf792ac3)
![SAs_f_l_t-detailed_model](https://github.com/MxHbm/Management-Science/assets/52173490/80f7f13b-901f-425b-a4c5-8caffd66c29b)
![RSs_t-family_aggregated_model](https://github.com/MxHbm/Management-Science/assets/52173490/da941f43-2880-4460-9bd0-d7d891f03b76)
![RSs_t-detailed_model](https://github.com/MxHbm/Management-Science/assets/52173490/2ad86b96-f54e-42a5-8bf0-27bcf8067b06)
![ROs_t-family_aggregated_model](https://github.com/MxHbm/Management-Science/assets/52173490/980b3a9b-61dd-438b-ad9d-dc2e4800d735)
![ROs_t-detailed_model](https://github.com/MxHbm/Management-Science/assets/52173490/c0ae3e5b-631d-41da-ae7f-edb0413c3868)
![RMt-family_aggregated_model](https://github.com/MxHbm/Management-Science/assets/52173490/1e5a2f6b-bc0e-4959-9cd8-7752b670146a)
![RMt-detailed_model](https://github.com/MxHbm/Management-Science/assets/52173490/427ec770-87c6-46ac-9436-249b3689977f)
![RIs_t-family_aggregated_model](https://github.com/MxHbm/Management-Science/assets/52173490/24dc01d4-1e6e-4047-aebe-7ed598ecb977)
![RIs_t-detailed_model](https://github.com/MxHbm/Management-Science/assets/52173490/a5ca2ef1-32be-4dd2-b629-12d09637c93d)
![RETURN-family_aggregated_model](https://github.com/MxHbm/Management-Science/assets/52173490/b8b65076-920c-4fbe-9cc4-144096ac5e93)
![RETURN-detailed_model](https://github.com/MxHbm/Management-Science/assets/52173490/225d48e8-b97e-4ce6-9e57-c755c9fbad3d)
![RCs_s-family_aggregated_model](https://github.com/MxHbm/Management-Science/assets/52173490/7686a6ce-31a9-4c18-99f8-391c5245fcc3)
![RCs_s-detailed_model](https://github.com/MxHbm/Management-Science/assets/52173490/ea823148-4762-4a02-bdd1-4d71aa81ac9b)
![R2m_t-family_aggregated_model](https://github.com/MxHbm/Management-Science/assets/52173490/84cef78a-c4f8-4fc2-b633-9313da78385f)
![R2m_t-detailed_model](https://github.com/MxHbm/Management-Science/assets/52173490/90df61a0-6a00-4c30-a515-f86a2daf467a)
![R1m_t-family_aggregated_model](https://github.com/MxHbm/Management-Science/assets/52173490/9c881f5f-d52b-48e5-a459-72d640821463)
![R1m_t-detailed_model](https://github.com/MxHbm/Management-Science/assets/52173490/54965412-7dda-4a4f-9bbe-3f6944cc59c3)
![Qm_t-family_aggregated_model](https://github.com/MxHbm/Management-Science/assets/52173490/21735c75-4f49-4eec-8618-3cfb6865c181)
![Qm_t-detailed_model](https://github.com/MxHbm/Management-Science/assets/52173490/055086db-0e05-4994-a4ce-98f897457301)
![PSp_l_t-family_aggregated_model](https://github.com/MxHbm/Management-Science/assets/52173490/fc7c4a1b-838e-4526-a220-aa4b9d07da6e)
![PSp_l_t-detailed_model](https://github.com/MxHbm/Management-Science/assets/52173490/1bfedb48-c01a-424c-a313-096ba0152c48)
![PDp_t-family_aggregated_model](https://github.com/MxHbm/Management-Science/assets/52173490/9d370f47-067f-4bdc-9679-318b0a9a7d11)
![PDp_t-detailed_model](https://github.com/MxHbm/Management-Science/assets/52173490/46589963-099f-4721-9162-a40ab3c587aa)
![OSs_f_l_t-family_aggregated_model](https://github.com/MxHbm/Management-Science/assets/52173490/4f5b592c-2706-43a5-ac44-61d3b404744d)
![OSs_f_l_t-detailed_model](https://github.com/MxHbm/Management-Science/assets/52173490/d567d503-2234-4ead-83e3-5bd07b7a35fa)
![OSDs_p_l_t-family_aggregated_model](https://github.com/MxHbm/Management-Science/assets/52173490/a109ae96-3b3d-4a9c-970d-71be3b3e8779)
![OSDs_p_l_t-detailed_model](https://github.com/MxHbm/Management-Science/assets/52173490/33e7db05-6c8e-476f-ad55-f76a34e1c4a7)
![MOm_t-family_aggregated_model](https://github.com/MxHbm/Management-Science/assets/52173490/e2c88c56-9981-44bf-9c37-72669dd92506)
![MOm_t-detailed_model](https://github.com/MxHbm/Management-Science/assets/52173490/4122a6c0-450b-4c65-979b-346ebc197532)
![IWIPm_t-family_aggregated_model](https://github.com/MxHbm/Management-Science/assets/52173490/c1d133db-776d-4a62-9b7f-62d9515878d5)
![IWIPm_t-detailed_model](https://github.com/MxHbm/Management-Science/assets/52173490/014a9bfd-f901-4fef-84ac-2f41d621bd72)
![IFf_t-family_aggregated_model](https://github.com/MxHbm/Management-Science/assets/52173490/89a1aeb5-cab2-4d3c-854c-08e97cc0c445)
![IFf_t-detailed_model](https://github.com/MxHbm/Management-Science/assets/52173490/9903741d-6815-4424-aee2-206c4e6ed663)
![IFDp_t-family_aggregated_model](https://github.com/MxHbm/Management-Science/assets/52173490/77335808-f7f5-42a8-ab69-da43550d61c2)
![IFDp_t-detailed_model](https://github.com/MxHbm/Management-Science/assets/52173490/d632ec23-02dd-4f6e-8b10-aebf1a478ccc)
![IDs_f_l_t-family_aggregated_model](https://github.com/MxHbm/Management-Science/assets/52173490/2ad847b0-79e6-459a-a73e-bb6eb1bab1b6)
![IDs_f_l_t-detailed_model](https://github.com/MxHbm/Management-Science/assets/52173490/1ef7d896-6a81-4aec-ac6f-473a83586f0e)
![IDDs_p_l_t-family_aggregated_model](https://github.com/MxHbm/Management-Science/assets/52173490/e627f5e8-3479-468d-a56e-fd3f56b383f4)
![IDDs_p_l_t-detailed_model](https://github.com/MxHbm/Management-Science/assets/52173490/b0280c93-0f4d-4ee7-bd9d-631a83b73f4a)
![FPf_t-family_aggregated_model](https://github.com/MxHbm/Management-Science/assets/52173490/0bc20166-8bf4-4fa0-8baa-02ed2269c0cd)
![FPf_t-detailed_model](https://github.com/MxHbm/Management-Science/assets/52173490/0823e7b2-63f4-41ae-a8d2-57a7e656ddcb)
![EXI-family_aggregated_model](https://github.com/MxHbm/Management-Science/assets/52173490/d111da34-c7b5-41ed-9b95-f4b870c02aa4)
![EXI-detailed_model](https://github.com/MxHbm/Management-Science/assets/52173490/0b9d9e01-abea-47cf-b54f-12e47d2d5bda)
![ENB-family_aggregated_model](https://github.com/MxHbm/Management-Science/assets/52173490/e95dfcb8-e439-4ceb-8d5e-6cdce67b8410)
![ENB-detailed_model](https://github.com/MxHbm/Management-Science/assets/52173490/f7b3b54f-f2ae-45b9-bdfe-c179bc589063)
![Ef_t-family_aggregated_model](https://github.com/MxHbm/Management-Science/assets/52173490/42e2e73d-395e-44ee-8ecc-7e792d208ba5)
![Ef_t-detailed_model](https://github.com/MxHbm/Management-Science/assets/52173490/4d99aa39-4b89-4ccf-88b3-69d210c42e78)
![EDp_t-family_aggregated_model](https://github.com/MxHbm/Management-Science/assets/52173490/299431d9-f3ae-49b3-b7e4-8a689a0a6191)
![EDp_t-detailed_model](https://github.com/MxHbm/Management-Science/assets/52173490/7ca84047-3d68-4467-afbf-c7a2d09dcd11)
![DVf_l_t-family_aggregated_model](https://github.com/MxHbm/Management-Science/assets/52173490/f523f77e-e89a-4bdf-b6a4-ee0e5267a56c)
![DVf_l_t-detailed_model](https://github.com/MxHbm/Management-Science/assets/52173490/65a1ed6d-85b5-4700-80ee-57ab359b6087)
![COST-family_aggregated_model](https://github.com/MxHbm/Management-Science/assets/52173490/f4aa39eb-488d-42e1-bcad-d18006a65e1a)
![COST-detailed_model](https://github.com/MxHbm/Management-Science/assets/52173490/931b99fd-303e-4b82-afb3-1137d2196fdf)

**Comment by b4ghir1** [comment]
Constraints Family Aggregated Model:

**Comment by b4ghir1** [comment]
Constraints Detailed Model:


![Constraint_63-detailed_model](https://github.com/MxHbm/Management-Science/assets/52173490/42d4ba3d-ab82-4114-a455-9c768a8016c4)
![Constraint_62-detailed_model](https://github.com/MxHbm/Management-Science/assets/52173490/41807023-9a1e-4800-8010-1a68b9a5cd30)
![Constraint_61-detailed_model](https://github.com/MxHbm/Management-Science/assets/52173490/2fbfb99b-ca07-4950-ba16-9d778506ee4e)
![Constraint_60-detailed_model](https://github.com/MxHbm/Management-Science/assets/52173490/2fa741d5-6fa0-450d-a17e-4a4e02a27783)
![Constraint_59-detailed_model](https://github.com/MxHbm/Management-Science/assets/52173490/107d7036-3648-4660-aaa7-fe5b5f02f574)
![Constraint_58-detailed_model](https://github.com/MxHbm/Management-Science/assets/52173490/dcd26ac4-d149-45d0-9124-5b16421613e3)
![Constraint_57-detailed_model](https://github.com/MxHbm/Management-Science/assets/52173490/37831b10-408e-4337-aedd-065655896940)
![Constraint_56-detailed_model](https://github.com/MxHbm/Management-Science/assets/52173490/b9f9dd53-0e8f-4400-affa-2308d28c6b7b)
![Constraint_55-detailed_model](https://github.com/MxHbm/Management-Science/assets/52173490/2694bedd-f868-433e-abad-2f427525ee9c)
![Constraint_54-detailed_model](https://github.com/MxHbm/Management-Science/assets/52173490/d2759304-48c0-47ac-8325-1d705338c44c)
![Constraint_53-detailed_model](https://github.com/MxHbm/Management-Science/assets/52173490/5b0b9e52-255d-4965-99d6-50820b6adef0)

**Comment by MxHbm** [comment]
Christoph glaubst du nicht, dass das ein bisschen zu viele Plots sind? BZw. wenn du den RHS wert ausgibst, was willst du damit zeigen?

**Comment by MxHbm** [comment]
@b4ghir1  Kannst du nochmal den gleichen Issue aufmachen, aber mit den Graphen aus meinem neuen BRanch? Jetzt haben zumindest mal die meisten Variablen Werte, also Z, A, Q etc.
